syntax = "proto3";
import "common/common.proto";

package client;

option java_package = "cn.jumiao.logic.ws.client";

enum RequestCode {
  INVALID_REQUEST = 0;
  PING = 1;
}

enum ResponseCode {
  INVALID_RESPONSE = 0;
  PONG = 1;
  ERROR = 2;
}



message Request {
  RequestCode cmd = 1;
  // 没有body的消息，可以不传body，但只要传了body，oneof 里的就必须设置一个
  RequestBody body = 2;
}

message RequestBody {
  oneof body {
    common.Empty demo = 1;
  }
}
message Response {
  ResponseCode cmd = 1;
  // 没有body的消息，可以不传body，但只要传了body，oneof 里的就必须设置一个
  ResponseBody body = 2;
}

message ResponseBody {
  oneof body {
    common.ErrorMessage error = 1;
  }
}
